const SET_PRODUCTS = "SET_PRODUCTS";
const ADD_PRODUCT = "ADD_PRODUCT";
const SET_SELECTED_PRODUCT = "SET_SELECTED_PRODUCT";
const SET_INVOICES = "SET_INVOICES";

export default {SET_PRODUCTS, ADD_PRODUCT, SET_SELECTED_PRODUCT, SET_INVOICES}